### ISSUE TITLE
Feature idea: detect sites that block font override and display info message to user

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/type-x#101]
Some sites, like Twitter and GitHub, block Type-X's functionality. This might be possible to detect and inform users about, so they don't think the extension is broken.

**Comment by RoelN** [comment]
I think this is already covered by https://github.com/arrowtype/type-x/issues/66 ?

**Comment by arrowtype** [comment]
Oh, yes, it is a duplicate of 66. My bad!
