### ISSUE TITLE
Font overrides are inconsistent on GitHub.com

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/type-x#22]
Sometimes, font overrides are not working on GitHub. So far, I am having trouble understanding when this will happen and when it won't. 

I have removed recursive fonts from my user fonts folder, to make sure that the fonts weren't just being loaded from my system, and now I find that GitHub isn't being overridden, consistently.

This is particularly strange, because wikipedia _is_ being overridden very consistently.

And just now, when I changed tabs to Wikipedia, took a screenshot, and came back, this issue page suddenly gained font overrides (even though they weren't there at first).

Is this something from how GitHub pages are rendered (e.g., maybe React or something is constructing the DOM in a way that the extension doesn't always override)? And then, when I come back to the page, maybe it tries to render again, and works, almost like kicking the machine makes it work? If so, is there any kind of "automatic kicking machine" we might be able to build in? (Credit to [ATP](https://atp.fm/episodes/324) for this name and idea).

![image](https://user-images.githubusercontent.com/7355414/58260769-044ecf80-7d45-11e9-90e1-29404c04fcd4.png)

![image](https://user-images.githubusercontent.com/7355414/58260886-46781100-7d45-11e9-9573-2c9a97ee0e70.png)

![image](https://user-images.githubusercontent.com/7355414/58260963-6c051a80-7d45-11e9-8fea-41a3161f7ce8.png)

**Comment by RoelN** [comment]
Closing this in favor of the specific CSP issue.
