### ISSUE TITLE
Text-oriented UI updates - "v1"

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/type-x#25]
As we chatted about, for v1 we will need to pair down our scope, and leave out some of the more-advanced UI controls for now.

With that in mind, I made some design polishing edits in https://github.com/kabisa/recursive-extension/pull/23, and then also did some directional sketches. 

Because we have (at least) three chunks of CSS to place with each font override, I think we would be best off using a tabbed approach within the overrides:

![image](https://user-images.githubusercontent.com/7355414/58291010-c3c57500-7d89-11e9-8d68-292aa30fcc4b.png)

Note: if we don't need the "apply changes" button, then we shouldn't change the top row to buttons – we can just leave it as it currently is.

![image](https://user-images.githubusercontent.com/7355414/58290976-a55f7980-7d89-11e9-8d37-e4c5c425be0d.png)

![image](https://user-images.githubusercontent.com/7355414/58290978-a8f30080-7d89-11e9-9d14-329634265afc.png)

![image](https://user-images.githubusercontent.com/7355414/58290983-aee8e180-7d89-11e9-8685-738f5f0aa207.png)

I do think that it would be more convenient to have a global selector blacklist, partly so a user can easily ignore weird hashes, etc, and doesn't risk accidentally deleting their work. However, if you think it's really better (or only feasible) to keep selectors to ignore with each font, here's how that might look:

![image](https://user-images.githubusercontent.com/7355414/58293994-de9de680-7d95-11e9-89be-b1626cc5e650.png)

**Comment by arrowtype** [comment]
Closing this as it's out-of-date, and resolved where applicable.
