### ISSUE TITLE
Dedicated landing page? -- pending decisions on Recursive Minisite

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/type-x#33]
It may or may not sense to create a dedicated landing page for this plugin, partially pending design decisions made on the Recursive minisite.

If we do decide to make a minisite, the page for Kap is a really excellent example of what this might be like:
- describes the thing, along with its requirements
- gives chance to sign up for email list for updates (not sure how important this is for Type-X)
- makes "download" very clear and easy
- links to GitHub repo for issues, license, privacy policy, and contributors
- links to website of the makers

![image](https://user-images.githubusercontent.com/7355414/58371586-9c34f080-7ee0-11e9-8c2e-e9b6a3993833.png)

**Comment by arrowtype** [comment]
Folding this into release prep, https://github.com/arrowtype/type-x/issues/18
