### ISSUE TITLE
Performance issues: lagging "apply edits" button, occassionally slow textarea typing

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/type-x#46]
Sometimes, the extension seems to get laggy.

> I think we're seeing a symptom of a viewport rendered inside an extension popup, not something specifically caused by this transition. So maybe leave out the comment and work with a issue specifically for this repaint/kick the machine stuff?

_Originally posted by @RoelN in https://github.com/kabisa/recursive-extension/pull/45_

Questions I have:
- Are variable font transitions causing any of this (i.e. the "type-x" slanting lable)?
- Does there need to be a debounce for calls to make the "apply edits" button show up? Currently, I think this is firing every time there is any change event in the form. However, it's such a small operation that it probably should slow things down noticeably.

**Comment by RoelN** [comment]
Seeing we don't have this button anymore, and I'm not seeing this slowness, _and_ we verified there aren't any complex animations/calculations happening, I prosopse to close this issue.
