### ISSUE TITLE
Example workflow for RoboFont

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/type-x#50]
I'm not quite sure where the best place is to post this, but I've found a nice prototyping workflow with RoboFont & Type-X, and wanted to note it down. Potentially, this could wind up in some docs, or potentially, I'll just refer people to this issue.

Workflow
1. Make some edits to a UFO in RoboFont.
2. Open `Font Info` and add a suffix after the Family Name. This suffix must change before each test install, so that your browser cache doesn't interfere with testing. So, it's useful to simply add a number, and increment that each time.
3. File > Test Install
4. Move to your Chrome browser, open Type-X on a testing webpage, and then find the new suffixed font name in the menu of a font override. 

That's it! A very simple workflow to test install and try fonts in the browser.

To update the test, just repeat steps 1–4.

**Comment by RoelN** [comment]
Sounds like a nice one for the [wiki](https://github.com/arrowtype/type-x/wiki). Keeps issues clean :-)

**Comment by arrowtype** [comment]
Good idea!

Added here: https://github.com/arrowtype/type-x/wiki/Workflow:-RoboFont-to-browser-tests
