### ISSUE TITLE
Live / auto update on user input

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/type-x#60]
Goal: for user input to update the web page, without requiring a click on "Apply Edits."

Possible implementation:

- Sliders and menus could probably apply changes on `change` events (possibly, after a small delay, but this should get tested – variable axis sliders are obviously most fun when they are totally-live)
- CSS fields should probably trigger an update on `blur`, to avoid trying to apply incomplete CSS with syntax errors

Possibly, we might benefit from keeping the "Apply Edits" button as a backup/secondary option for changes made in text fields. This would help users to know they can apply edits, without them having to tab or click out of the text field.

**Comment by arrowtype** [comment]
The updates in the `auto-update` branch are super nice!

One thing that I do feel, though: while using it, there’s a small but intense delay between user changes and their insertion into page styles. Overall, it’s performing waaay better than I thought it might ever achieve, so I’m stoked about it. However, that pause is just enough time for me to wonder, “will it work this time?” 

So, I think it would go a really long way to add some type of “loading” animation. That is, if we could trigger some kind of loading animation as soon as a change is detected, then hide it as soon as the change is applied, it would really help users to have confidence that their changes are being applied, and (I think) make things feel much snappier overall

My thought is that this would generally be one of two animations: a spinner or a loading bar.

A spinner could be shown on changes, then hidden on completion of adding changes. The advantage of this approach is that it's (probably) simpler to implement.

![image](https://user-images.githubusercontent.com/45946693/66340376-050e8980-e913-11e9-9e88-6c7eb39c48a3.png)

A loading bar would be a bit trickier, probably – I think we would have to cue it when a change is detected, make it progress, and then let it pause a bit before the end, until we know changes are complete. I haven't built something quite like this, so I'm not entirely sure how to do that. This sort of loading bar is similar to what shows up at the top of the page when you navigate to different pages within GitHub.

![image](https://user-images.githubusercontent.com/45946693/66340383-0b9d0100-e913-11e9-86bc-9e6b5a5ffc26.png)

Does this kind of thing seem feasible, @pixelambact, or what are your thoughts? If you do like one of the above approaches, I could design a specific SVG for it.

**Comment by RoelN** [comment]
Loader has been added (to the page itself). Please re-open if you feel not all points have been addressed!
