### ISSUE TITLE
Not found in Chrome Web Store

### ISSUE THREAD

**Issue by etunni** [arrowtype/type-x#61]
Can you provide me the link for install Type-X from Chrome Web Store because I don't found it?.
Thanks
Eduardo Tunni

**Comment by thundernixon** [comment]
Hey Eduardo, thanks for your interest!

We will be putting Type-X on the chrome web store soon, but if you'd like to use it right now, you can follow the instructions in the readme to install in developer mode.

https://github.com/arrowtype/type-x#installation

**Comment by etunni** [comment]
Hey,

I downloaded Type-X from GH but don’t know how install it.

With terminal?

Cheers
Edu

**Comment by arrowtype** [comment]
Good question! Thanks for asking.

Actually, the `dist` folder is already built, so you can just do this:

1. Go to `chrome://extensions` in Chrome browser
1. Turn on "Developer Mode" with the toggle in the top-right corner
1. Click "Load unpacked" and navigate to the `dist` folder of the repo you cloned – alternatively, you can just drag-n-drop this `dist` folder into the extensions page.

I'll add this `dist` folder into the repo's releases page, to make this easier for the next person.

**Comment by etunni** [comment]
Your are the best!!

Cheers,
Edu

PS: Do you used or know Tunni Lines in Type-design?

**Comment by arrowtype** [comment]
> Do you used or know Tunni Lines in Type-design?

Haha, I definitely do sometimes! You came up with that, right?

**Comment by etunni** [comment]
> Haha, I definitely do sometimes! You came up with that, right?
> 
Yes, but is controvertial for some type designers :)

FontLab has the real implementation of the Yunni-lines

Cheers.
Edu

**Comment by RoelN** [comment]
Closing this issue as it looks to be solved :-)
