### ISSUE TITLE
feature suggestion: load fonts from URL

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/type-x#63]
(Like on google fonts.)

This was an idea that came up in the conversation after a live demo at Type Thursday. It was suggested by a web dev/designer, and I filed this as an issue, to give a live demo of how to file an issue on GitHub.

Another participant expressed concern that this may infringe on EULAs.

Personally, I think this _could_ be a nice-to-have feature, but unless it comes up independently from a few more developers in the future, I don't quite feel like it is a high priority. It would add complexity to the UI & codebase, and raise quite a few challenging questions around _what_ URLs people would feed in. I suppose maybe google fonts CSS imports are the most likely candidate? Still, for such fonts, it seems that it would be a relatively small advantage to allow, but nothing groundbreaking.

**Comment by RoelN** [comment]
While I see how this could be useful, I think this goes beyond the scope of the tool: TypeX lets you check your local fonts on websites, to verify how they look "in the wild". It's not a "surf the web in Google Fonts fonts" tool.

To keep the number of issues down & relevant, I propose to close this one. Feel free to re-open if you feel differently!
