### ISSUE TITLE
User Experience & UI – Balancing Simplicity & Flexibility -"v2"

### ISSUE THREAD

**Issue by thundernixon** [arrowtype/type-x#7]
The question I've tried to come up with an answer to:

> Where to draw the line? Keep it simple, or keep it flexible?

My short answer: I'm hoping to make this a useful tool for moderately-technical designers.
- e.g. a product designer wants to test out what a new font might look like in their product
- e.g. a type designer wants to test a WIP font, to see how it reads in familiar sites

Conclusion:
- We can make the tool useful for anyone who can click buttons
- We can make the tool _more_ useful for anyone who can find, copy, and paste  (or write) CSS, to have fuller control over things like element selection and styles

# Draft of UI

I've tried to simplify this as much as possible, but I recognize that it might still be more complex than is within scope. I also realize that as much thought as I've put into this, I've probably forgotten things. So, feel free to use your judgment on what next steps to take!

I made these mockups in Sketch, but in case you'd like to grab colors, see measurements, export icons, etc etc, I have imported the file to Figma and shared a link through a DM to @kabisa on Slack.

<details>
<summary><b>User Journey</b></summary>

The first view of the extension is simple. Click a button to activate fonts, or click to open extension settings.

![image](https://user-images.githubusercontent.com/7355414/57747704-b67efb00-76a4-11e9-91a3-902f96843e90.png)

![image](https://user-images.githubusercontent.com/7355414/57747426-871bbe80-76a3-11e9-9d3d-07379e7dcf75.png)

By default, there are two fonts loaded. One overrides headlines and text, while the other overrides code.

![image](https://user-images.githubusercontent.com/7355414/57747445-9f8bd900-76a3-11e9-9ae5-3bb09f196ac5.png)

The user wants to change the font. They can click the menu to see previously-loaded fonts.

![image](https://user-images.githubusercontent.com/7355414/57747665-80da1200-76a4-11e9-867c-19f7fc96d6da.png)

They decide to "add another font" or to expand the font family options. Either way, the get the option to drag-n-drop a new font (ideally, this could also pull up a system file window if clicked):

![image](https://user-images.githubusercontent.com/7355414/57747680-9b13f000-76a4-11e9-812d-5e179203fff4.png)

The user wants to change the font style. Clicking the style menu would show instances. The expand-options caret gives a small panel for CSS properties:

![image](https://user-images.githubusercontent.com/7355414/57747698-af57ed00-76a4-11e9-93d4-fb6c14ab69f8.png)

The user can either make a simple selection of which 3 types of content they wish to override (headlines, text, and/or code), or expand to see all the selectors that are included:

![image](https://user-images.githubusercontent.com/7355414/57747785-0eb5fd00-76a5-11e9-978d-b74b850d0b7e.png)

Maybe the user wants to add more icon override selectors. Here, I think "don't override" is probably clearer than "blacklist." The user can expand this section to add selectors which should be ignored. This is useful to help them cover sites and selectors we couldn't predict beforehand (like the random-string class names on sites like Google Calendar and Styled Components).

![image](https://user-images.githubusercontent.com/7355414/57748007-f7c3da80-76a5-11e9-8350-4463cd58a4ad.png)

Maybe, the user wants to add a third font. This logic starts to get a bit tricky, but right now, my assumption is that we should allow a "cascade," so that newer fonts override earlier fonts. This could potentially be shown by striking out the override values in the earlier font.

We should probably discuss this before deciding exactly what to do, here.

![image](https://user-images.githubusercontent.com/7355414/57748135-a7994800-76a6-11e9-9077-3835921e3a34.png)

If this exceeds something like 95vh, the control panel with do an `overflow-y: auto;`

</details>

### Assumptions:

- These settings persist between websites. The user doesn't have a way to export/import/share settings.
- Fonts which are loaded can (hopefully) persist between browser visits.

**Comment by arrowtype** [comment]
I'm going to close this, as I feel that we've either achieved most of it already or else have separated specific goals into other issues.
