### ISSUE TITLE
Refine design of "reset" button

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/type-x#71]
https://github.com/arrowtype/type-x/commit/6cb827aa39b6ba5b1917a6ef2404c8353907e375 adds a very useful "reset" button, so users can bail out if they have run into a bug or have just added too many fonts and overrides and want to start fresh.

However, I think maybe we can refine the design of it by a bit. In the current iteration, I worry that it clutters the footer in a way that might be a bit confusing. Not only do things get a bit crowded, but also the footer goes from `[credits] [repo]` to `[credits] [UI action] [repo]`, so it mixes user actions into the metadata.

![image](https://user-images.githubusercontent.com/45946693/68605192-f703d980-0479-11ea-9cf2-83252c855ee9.png)

My current thinking is that it might be best to place this reset button into the "overrides" header:

![image](https://user-images.githubusercontent.com/45946693/68604954-907ebb80-0479-11ea-976d-2643eb27b30d.png)

This way, it makes it very clear to users that this is a "quick use" extension. It's not meant for long-term site customization, a la extensions such as Stylus, but is rather a tool to quickly test out fonts.

Of course, as a destructive action, it should visually indicate this to users by using similar styling as the "delete" button that is already in individual font overrides.

The one downside I can think of: this button might be _too_ simple to click, and might not be obvious enough as a highly-destructive action (users might spend many minutes configuring overrides, and then might unintentionally click this button). 

Therefore, it might ideally be paired with either a confirmation dialog (e.g. "Are you sure you want to permanently delete overrides and clear your loaded fonts from the font menu?") or an undo (e.g. "You have deleted font overrides and clear your loaded fonts. [Undo](#)?"). However, this would be a separate feature/issue.

@RoelN do you have any thoughts on this? I could probably do the styling legwork on it and make a PR, which you could maybe review it, time permitting.

Note: I also considered putting this near the bottom, but it clashes with “selectors to ignore,” and I think it might confuse people about whether they are reseting the whole thing, or just selectors
I’m still not 100% sure of my design above, but i think it might be our best option, short of adding a context menu or something (which would cause new problems). I _also_ considered placing it in the very top bar, but that would be quite confusing, because then users might see it as a "refresh page" option rather than something tied to override configuration.

**Comment by RoelN** [comment]
Even if Type-X would be a "quick use extension", it indeed feels too prominent. The UI is starting to feel a little bit scattered, too. Could we maybe group stuff into three main parts?

1. Title — big on/off button — expand button
2. List of fonts
3. Actions: add, reset, edit ignore-list

(With the footer being a subtle fourth part)

Quick hacky mockup:
<img width="754" alt="image" src="https://user-images.githubusercontent.com/4570664/68751866-a075d700-0602-11ea-9a49-498c2ff5af66.png">
