### ISSUE TITLE
Recursive font & axis sliders should be updated to more-current versions of Recursive, due to changed axis names & defaults

### ISSUE THREAD

**Issue by arrowtype** [arrowtype/type-x#88]
The bottom font override that happens by default shows `MONO=1`, but doesn’t actually use monospace styles to override code on web pages.

This is because the _default_ of that axis was changed _in Recursive_ after we had already mostly wrapped up work on this extension. But, the slider probably has a `value="0"` attribute to start, so it shows one thing without applying it, and the font shows its default (`MONO=0`). 

While this is being fixed, it would be worthwhile to also update to the latest version of Recursive:

https://github.com/arrowtype/recursive/releases/latest

And update the `Italic` axis label to `Cursive`, as it now is in Recursive.

Finally, the axes should be specifically ordered, rather than alphabetical:

1. `MONO`
2. `CASL`
3. `wght`
4. `slnt`
5. `CRSV`

![image](https://user-images.githubusercontent.com/45946693/97083260-be063b80-15dc-11eb-9977-92f0e2c9acf2.png)

**Comment by RoelN** [comment]
Font has been updated. Addressing the ordering in: https://github.com/arrowtype/type-x/issues/91
